### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by Petrarca181** [shupkat/RanobeLib2Epub#1]
![image](https://github.com/shupkat/RanobeLib2Epub/assets/54235138/c63a9e08-e4d2-470e-b07e-b0134638db99)

**Comment by shupkat** [comment]
На сайте временно ставили cloudflare защиту которую не получалось обойти обычными запросами, но теперь всё снова работает.

**Comment by shupkat** [comment]
На сайте временно ставили cloudflare защиту которую не получалось обойти обычными запросами, но теперь всё снова работает.
