### ISSUE TITLE
А как собственно, запустить скрипт? 

### ISSUE THREAD

**Issue by OkomuraSan** [shupkat/RanobeLib2Epub#11]

**Comment by OkomuraSan** [comment]
Вообщем, запустил я проект через pycharm, однако чё-то не так с библиотекой prosemirror. Я поискал, оказалось, что проблема у большинства юзеров этой библиотеки. Вроде как разрабы чё-то мутят. Вообщем, надо держать руку на пульсе и смотреть что они там придумают
![image](https://github.com/user-attachments/assets/bec7e70e-3909-404e-86a8-a0978553bfc7)

**Comment by shupkat** [comment]
Попробуйте установить версии библиотек из файла requirements.txt с помощью команды `pip install -r requirements.txt` находясь в директории с скриптом. Запустить скрипт можно с помощью файла main.py
