### ISSUE TITLE
На 2 новеллы с четырёх выскакивет ошибка

### ISSUE THREAD

**Issue by Alla183** [shupkat/RanobeLib2Epub#12]
Качаю 18+, токен есть, работает, но некоторые не хочет скачивать. 
![image](https://github.com/user-attachments/assets/c791f4b4-9118-4741-bacd-20dbdcf42677)

**Comment by shupkat** [comment]
Вроде исправил. Проблема была в том что сайт не указывал переводчика для определённых глав (например для главы 19 в примере из скриншота), теперь скрипт скачивает такие главы, чтобы отключить это нужно добавить флаг -n при запуске скрипта
