### ISSUE TITLE
Ошибка парсинга

### ISSUE THREAD

**Issue by KostanKettch** [shupkat/RanobeLib2Epub#2]
При скачивании возникает ошибка
 `Traceback (most recent call last):
  File "C:\Users\Radmira\ranobeparser\RanobeLib2Epub\chapter_parser.py", line 17, in parse_chapter
    content = BeautifulSoup(r["content"], "lxml")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\bs4\__init__.py", line 328, in __init__
    for (self.markup, self.original_encoding, self.declared_html_encoding,
  File "C:\Python311\Lib\site-packages\bs4\builder\_lxml.py", line 182, in prepare_markup
    DetectsXMLParsedAsHTML.warn_if_markup_looks_like_xml(markup)
  File "C:\Python311\Lib\site-packages\bs4\builder\__init__.py", line 535, in warn_if_markup_looks_like_xml
    and markup.startswith(prefix)
        ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'startswith'`

**Comment by shupkat** [comment]
Привет, дай ссылку с которой пытаешься скачать, а так же вывод команд `pip list` и `python --version`

**Comment by KostanKettch** [comment]
https://ranobelib.me/ru/book/6689--ascendance-of-a-bookworm-novel
При скачивании перевода 0 падает на томе 20 (тома 1-19 скачиваются нормально)
При скачивании перевода 1 падает сразу.


pip list
` Package            Version`
---------------- --------
`APScheduler        3.10.1`
`beautifulsoup4     4.12.2`
`certifi            2024.2.2`
`charset-normalizer 3.3.2`
`colorama           0.4.6`
`decorator          4.4.2`
`EbookLib           0.18`
`idna               3.7`
`imageio            2.34.1`
`imageio-ffmpeg     0.4.9`
`iso8601            2.1.0`
`loguru             0.7.0`
`lxml               5.2.2`
`m3u8               3.4.0`
`moviepy            1.0.3`
`multidict          6.0.5`
`mutagen            1.46.0`
`numpy              1.26.4`
`pillow             10.3.0`
`pip                24.0`
`proglog            0.1.10`
`pyaes              1.6.1`
`pycryptodome       3.17`
`Pyrogram           2.0.103`
`PySocks            1.7.1`
`python-slugify     8.0.1`
`pytz               2024.1`
`PyYAML             6.0`
`requests           2.31.0`
`setuptools         65.5.0`
`six                1.16.0`
`soupsieve          2.5`
`text-unidecode     1.3`
`TG-AutoPoster      3.5.0`
`TgCrypto           1.2.5`
`tqdm               4.66.4`
`tzdata             2024.1`
`tzlocal            5.2`
`urllib3            2.2.1`
`vk-api             11.9.9`
`wget               3.2`
`win32-setctime     1.1.0`
`yarl               1.9.4`

python --version
`Python 3.11.5`

**Comment by shupkat** [comment]
На сайт, похоже, добавили новый редактор глав для тех, кто их загружает. Теперь некоторые главы идут в другом формате. Поддержку этого формата я добавил, но возможны проблемы с форматированием и изображениями. Если такие проблемы возникнут, создай новый issue и оставьте ссылку на ранобэ.
