### ISSUE TITLE
все кроме одной книги работает

### ISSUE THREAD

**Issue by essemet** [shupkat/RanobeLib2Epub#3]
![ranobe](https://github.com/shupkat/RanobeLib2Epub/assets/173602863/90cf4c9c-4847-4f43-91e1-51c812885404)

**Comment by shupkat** [comment]
Обновил скрипт. Добавил поддержку авторизации для доступа к закрытым страницам.
https://github.com/shupkat/RanobeLib2Epub/blob/main/howToAuth.md
