### ISSUE TITLE
 Problems running the script

### ISSUE THREAD

**Issue by notEvil666** [shupkat/RanobeLib2Epub#4]
Столкнулся с проблемой при запуске скрипта (снимок ниже). Не знаю, как решить эту ошибку. Возможно, я что то делаю не так и не там, впервые приходится запускать скрипты python. Скрипт запускал и в powershell, и в cmd, результат один. Использую Windows 8.1. Надеюсь на вашу помощь.

(Eng)
I encountered a problem when running the script (picture below). I don't know how to solve this error. Perhaps I'm doing something wrong and in the wrong place, this is the first time I have to run python scripts. I ran the script in both powershell and cmd, the result was the same. I use Windows 8.1. I am hope for your help.
![Снимок](https://github.com/shupkat/RanobeLib2Epub/assets/91894735/50f20e4c-29f5-4e2c-b3c2-331fda203ed3)

**Comment by shupkat** [comment]
Попробуйте скачать версию python 3.9 и выше

**Comment by notEvil666** [comment]
Большое спасибо, теперь всё работает.

**Comment by Alla183** [comment]
Здравствуйте, битый час вожусь и все не так....

![Screenshot 2024-07-23 121648](https://github.com/user-attachments/assets/e027056e-5037-446d-91c2-1d1ead1aad79)
![Screenshot 2024-07-23 121821](https://github.com/user-attachments/assets/49052e01-278a-48d1-b8b4-b0aeca6d876a)
